import { NavbarV0 } from "@/components/component/navbar-v0";
import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Codefury 7 - Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavbarV0 />
      {children}
    </div>
  );
}
