import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Translator from "@/components/Translator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Codefury 7 - Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster richColors closeButton />
          {children}
          <div className="fixed bottom-2 left-2 bg-muted border p-2 rounded">
            <Translator />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
